# Codemagic CI/CD for Gezondheids Tracker - iOS
# Create group "api_config" in Codemagic > Settings > Environment variables
# Add variable: APIURL = https://eczemacare.onrender.com
#
# For code signing: add "ios_credentials" group with distribution cert + provisioning profile

workflows:
  ios-release:
    name: iOS Release
    working_directory: .  # Use GezondheidsTrackerFlutter if app is in subfolder
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - api_config
      vars:
        BUILD_TYPE: "release"
        BUNDLE_ID: "com.example.gezondheidsTracker"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: |
          echo "Building iOS with API: $APIURL"
          flutter build ipa --release --dart-define=APIURL=$APIURL
    artifacts:
      - build/ios/ipa/*.ipa
