# Codemagic CI/CD for Gezondheids Tracker
# Create group "api_config" in Codemagic > Settings > Environment variables
# Add variable: API_URL = https://eczemacare.onrender.com

workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      groups:
        - api_config  # Matches the group name created in the UI
      vars:
        BUILD_TYPE: "release"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: |
          echo "Building with API: $API_URL"
          flutter build apk --release --dart-define=API_URL=$API_URL
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
