# Codemagic CI/CD for Gezondheids Tracker - iOS
# Group "apiconfig" in Codemagic > Environment variables
# Variable: APIURL = https://eczemacare.onrender.com
#
# For code signing: add "ios_credentials" group with distribution cert + provisioning profile

workflows:
  ios-release:
    name: iOS Release
    working_directory: .  # Use GezondheidsTrackerFlutter if app is in subfolder
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - apiconfig
      vars:
        BUILD_TYPE: "release"
        BUNDLE_ID: "com.example.gezondheidsTracker"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS
        script: |
          # Find Flutter app (must have pubspec.yaml AND lib/main.dart)
          find_flutter_app() {
            for dir in . GezondheidsTrackerFlutter EczemaCare app mobile flutter_app; do
              if [ -f "$dir/pubspec.yaml" ] && [ -f "$dir/lib/main.dart" ]; then
                echo "$dir"
                return
              fi
            done
            PROJ=$(find . -path "*/lib/main.dart" -maxdepth 5 2>/dev/null | head -1)
            if [ -n "$PROJ" ]; then
              dirname "$(dirname "$PROJ")"
              return
            fi
            echo ""
          }
          FLUTTER_DIR=$(find_flutter_app)
          if [ -z "$FLUTTER_DIR" ]; then
            echo "ERROR: No Flutter app (pubspec.yaml + lib/main.dart) found. Repo contents:"
            ls -la
            find . -name "pubspec.yaml" -o -name "main.dart" 2>/dev/null | head -20
            exit 1
          fi
          cd "$FLUTTER_DIR"
          echo "Using Flutter app at: $FLUTTER_DIR"
          flutter pub get
          flutter create . --platforms=ios
          echo "Building iOS with API: $APIURL"
          flutter build ipa --release --dart-define=API_URL=$APIURL
    artifacts:
      - "**/build/ios/ipa/*.ipa"
